## Kelompok Alin B-01 Soal No 13

### Anggota Kelompok

1. Rafa Huga Nirando / 5025241113
2. Raditya Zhafran Pranuja / 5025241120
3. Melvan Hapianan Allo Ponglabba / 5025241124
4. Mochammad Irfan Sandy / 5025241127
5. Hatta Adzikra Fadly / 5025241182

### Soal

Mencari determinan sebuah matrix menggunakan Gauss

    |  4  6 -3 -2 |
    | -8 -1  8 -3 |
    |  9  9 -2 -3 |
    |  4 -5  3  7 |

## Code Gauss Jordan

### Import Module dan Set Global Variabel Iterasi

Import library bernama numpy agar lebih mudah memanipulasi matrix. Dan tambahkan variabel global iterasi agar semua fungsi bisa mengakses variabel tersebut

In [10]:
import numpy as np

iteration = 0

### Membuat Fungsi Input

Pertama kita membuat function input matrix yang mengeluarkan datatype numpy.ndarray (numpy n dimensional array). Lalu kita ambil input dari user berupa baris matrix dan kolom matrix. Setelah itu input tersebut di cek jika salah satu baris/kolom bernilai dibawah nol maka input salah. 

Lalu user menginput baris * kolom integer yang berbentuk string yang akan di split berdasarkan spasi dan diubah ke integer menggunakan map yang kemudian di ubah ke bentuk list. Lalu jumlah input dicek apabila tidak memenuhi baris * kolom atau user menginput selain integer. Lalu list tersebut diubah ke numpy.ndarray yang memiliki datatype np.float64 dan dibentuk sesuai baris dan kolomnya.

In [11]:
def inputMatrix() -> np.ndarray:
    try:
        n = int(input("Masukkan Jumlah Baris: "))
        m = int(input("Masukkan Jumlah Kolom: "))
    
        if n <= 0 or m <= 0:
            raise ValueError("Jumlah Baris dan Kolom harus lebih besar dari 0")
    
        matrix = list(map(int, input("Masukkan koefisien-koefisien variabel: ").split()))
    
        if len(matrix) != n * m:
            raise ValueError("Jumlah Koefisien Tidak Sesuai")
        return np.array(matrix, dtype=np.float64).reshape(n, m)
    except ValueError as e:
        print(f'Input Error: {e}')
        exit(0)

### Membuat Fungsi Pembantu Gauss Jordan

Operasi basis elementer (elementary basis operation) mengubah sebuah matrix ke bentuk eselon baris (row echelon form) atau (reduced row echelon form) dengan menggunakan 3 macam perhitungan. Yaitu tukar baris (row swap), kali skalar baris (row scalar multiplication), dan penjumlahan baris (row sum).

1. Tukar baris terjadi apabila baris teratas yang belum memiliki leading 1 / pivot, kolom pada baris tersebut memiliki nol dan pada baris lainnya terdapat angka yang tidak nol.

2. Kali skalar baris terjadi karena dalam pencarian leading 1 / pivot sebuah baris akan dibagi oleh baris kolom pivot yang akan dicari agar mendapatkan angka 1.

3. Penjumlahan baris digunakan untuk membuat nol baris lain pada suatu kolom pivot / leading 1.
   
Penjelasan fungsi:
1. Fungsi rowSwap() menerima input matrix berbentuk numpy.ndarray, baris yang ingin ditukar dan baris yang akan ditukar, dan fungsi tersebut mereturn None atau Void function. Fungsi tersebut menambah global iteration, print apa yang akan dilakukan, menukar baris awal dan akhir, dan print matrix berupa numpy.ndarray.

2. Fungsi rowDivide() menerima input matrix berbentuk numpy.ndarray, baris yang akan dibagi, dan kolom letak pivot / leading 1 dan mereturn None atau Void function. Fungsi tersebut menambah global iteration, print apa yang akan dilakukan, membagi baris dengan angka yang akan diubah ke 1, membulatkan 2 angka belakang koma, dan print matrix berupa numpy.ndarray.

3. Fungsi rowSum() menerima input matrix berbentuk numpy.ndarray, baris yang akan ditambah, baris penambah dan kolom letak pivot / leading 1 dan mereturn None atau Void function. Fungsi tersebut menambah global iteration, print apa yang akan dilakukan, menambah baris tujuan dengan baris pivot * kolom pivot baris tujuan, membulatkan 2 angka belakang koma, dan print matrix berupa numpy.ndarray.

In [12]:
def rowSwap(matrix: np.ndarray, rowStart: int, rowEnd: int) -> None:
    global iteration
    iteration += 1
    print(f'Iteration: {iteration}\nSwapping Row {rowStart+1} and {rowEnd+1}')
    matrix[[rowStart, rowEnd]] = matrix[[rowEnd, rowStart]]
    print(f'{matrix}\n')

def rowDivide(matrix: np.ndarray, row: int, pivotLocation: int) -> None:
    global iteration
    iteration += 1
    print(f'Iteration: {iteration}\nDividing Row {row+1} by {matrix[row, pivotLocation]}')
    matrix[row] = matrix[row] / matrix[row, pivotLocation]
    np.around(matrix, 2, matrix)
    matrix = np.where(matrix == -0, 0, matrix)
    print(f'{matrix}\n')
    
def rowSum(matrix: np.ndarray, row: int, curRow: int, curCol: int) -> None:
    global iteration
    iteration += 1
    print(f'Iteration: {iteration}\nSubtracting Row {row+1} by {matrix[curRow, :] * matrix[row, curCol]}')
    matrix[row, :] = matrix[row, :] - (matrix[curRow, :] * matrix[row, curCol])
    np.around(matrix, 2, matrix)
    matrix = np.where(matrix == -0, 0, matrix)
    print(f'{matrix}\n')

### Fungsi Gauss Jordan

Fungsi gaussjordan() ini seperti namanya melakukan operasi basis elementer (elementary row operation) sehingga mendapatkan identity matrix. Fungsi ini menerima input matrix berupa numpy.ndarray dan mengoutput None atau Void Function. 

Secara garis besar fungsi ini mengecek apakah kolom sekarang (curRow) kosong. Jika iya dia pindah kolom. Lalu fungsi ini mengecek apakah pada kolom yang akan dicari pivotnya baris teratas yang tidak memiliki pivot bukan nol. Jika tidak maka akan di tukar dengan baris yang angkanya tidak nol. Lalu akan dilakukan kali skalar baris dan menyimpan letak pivot untuk dilakukan pengeliminasian angka diatas pivot.

Setelah itu angka dibawah pivot di nol kan dengan penjumlahan baris. Apabila yang keluar adalah baris nol maka akan ditukar ke bawah dengan baris yang tidak nol. Lalu kolom dan baris ditambah satu.

Jika baris atau kolom sekarang melebihi baris atau kolom sebenarnya maka akan dilakukan step kedua yaitu meng nol kan angka diatas pivot dengan penjumlahan baris.

In [13]:
def gaussjordan(matrix: np.ndarray) -> None:
    global iteration
    iteration = 0
    mrow, mcol = matrix.shape
    zeroVectorSwap = 0
    pivot = []
    doSum = False
    curRow = 0
    curCol = 0
    
    print(f'Input Matrix\n{matrix}\n')
    
    while curCol < mcol and curRow < mrow:
        if not doSum and not np.any(matrix[curRow:, curCol]):
            curCol += 1
        elif not doSum:
            for i in range(curRow, mrow):
                if matrix[i, curCol] != 0:
                    if i != curRow: rowSwap(matrix, curRow, i)
                    if matrix[curRow, curCol] != 1: rowDivide(matrix, curRow, curCol)
                    pivot.append([curRow, curCol])
                    doSum = True
                    break
        else:
            for i in range(curRow+1, mrow):
                if matrix[i, curCol] != 0:
                    rowSum(matrix, i, curRow, curCol)
                    if not np.any(matrix[i, :]) and not i >= mrow - 1 - zeroVectorSwap:
                        for j in range(mrow-1, -1, -1):
                            if np.any(matrix[j, :]):
                                determinant = determinant * -1
                                rowSwap(matrix, i, j)
                                zeroVectorSwap += 1
                                rowSum(matrix, i, curRow, curCol)
                                break
                    elif not np.any(matrix[i, :]) and i == mrow - 1 - zeroVectorSwap:
                        zeroVectorSwap += 1
            doSum = False
            curCol += 1
            curRow += 1
            
    for i in range(len(pivot)-1, -1, -1):
        for j in range(pivot[i][0]-1, -1, -1):
            if matrix[j, pivot[i][1]] != 0:
                rowSum(matrix, j, pivot[i][0], pivot[i][1])

### Fungsi Main

Fungsi yang telah dibuat tadi akan dijalankan di "if __name__ == '__main__':" block dengan input matrix 4x4 yaitu:

    |  4  6 -3 -2 |
    | -8 -1  8 -3 |
    |  9  9 -2 -3 |
    |  4 -5  3  7 |

In [14]:
if __name__ == '__main__':
    matrix = np.array([4, 6, -3, -2, -8, -1, 8, -3, 9, 9, -2, -3, 4, -5, 3, 7], dtype=np.float64).reshape(4, 4)
    gaussjordan(matrix)

Input Matrix
[[ 4.  6. -3. -2.]
 [-8. -1.  8. -3.]
 [ 9.  9. -2. -3.]
 [ 4. -5.  3.  7.]]

Iteration: 1
Dividing Row 1 by 4.0
[[ 1.    1.5  -0.75 -0.5 ]
 [-8.   -1.    8.   -3.  ]
 [ 9.    9.   -2.   -3.  ]
 [ 4.   -5.    3.    7.  ]]

Iteration: 2
Subtracting Row 2 by [ -8. -12.   6.   4.]
[[ 1.    1.5  -0.75 -0.5 ]
 [ 0.   11.    2.   -7.  ]
 [ 9.    9.   -2.   -3.  ]
 [ 4.   -5.    3.    7.  ]]

Iteration: 3
Subtracting Row 3 by [ 9.   13.5  -6.75 -4.5 ]
[[ 1.    1.5  -0.75 -0.5 ]
 [ 0.   11.    2.   -7.  ]
 [ 0.   -4.5   4.75  1.5 ]
 [ 4.   -5.    3.    7.  ]]

Iteration: 4
Subtracting Row 4 by [ 4.  6. -3. -2.]
[[  1.     1.5   -0.75  -0.5 ]
 [  0.    11.     2.    -7.  ]
 [  0.    -4.5    4.75   1.5 ]
 [  0.   -11.     6.     9.  ]]

Iteration: 5
Dividing Row 2 by 11.0
[[  1.     1.5   -0.75  -0.5 ]
 [  0.     1.     0.18  -0.64]
 [  0.    -4.5    4.75   1.5 ]
 [  0.   -11.     6.     9.  ]]

Iteration: 6
Subtracting Row 3 by [-0.   -4.5  -0.81  2.88]
[[  1.     1.5   -0.75  -0.5

## Code Determinant Dengan Gauss

### Fungsi Mencari Determinan Menggunakan Gauss

Fungsi gaussDeterminant() ini sama seperti gaussJordan() tetapi letak perbedaannya terdapat pada output dan steps nya. Fungsi ini mereturn float yaitu determinant sebuah matrix.

Determinant akan terpengaruh apabila:
1. Operasi basis elementer swap row akan mengalikan Determinant sementara dengan -1
2. Operasi basis elementer kali skalar baris akan mengalikan Determinant sementara dengan pengali nya

In [15]:
def gaussDeterminant(matrix: np.ndarray) -> float:
    global iteration
    iteration = 0
    mrow, mcol = matrix.shape
    determinant:float = 1
    zeroVectorSwap = 0
    doSum = False
    curRow = 0
    curCol = 0
    
    print(f'Input Matrix\n{matrix}\n')
    
    while curCol < mcol and curRow < mrow:
        if not doSum and not np.any(matrix[curRow:, curCol]):
            curCol += 1
        elif not doSum:
            for i in range(curRow, mrow):
                if matrix[i, curCol] != 0:
                    if i != curRow: 
                        determinant = determinant * -1
                        rowSwap(matrix, curRow, i)
                    if matrix[curRow, curCol] != 1: 
                        determinant = determinant * matrix[curRow, curCol]
                        rowDivide(matrix, curRow, curCol)
                    doSum = True
                    break
        else:
            for i in range(curRow+1, mrow):
                if matrix[i, curCol] != 0:
                    rowSum(matrix, i, curRow, curCol)
                    if not np.any(matrix[i, :]) and not i >= mrow - 1 - zeroVectorSwap:
                        for j in range(mrow-1, -1, -1):
                            if np.any(matrix[j, :]):
                                determinant = determinant * -1
                                rowSwap(matrix, i, j)
                                zeroVectorSwap += 1
                                rowSum(matrix, i, curRow, curCol)
                                break
                    elif not np.any(matrix[i, :]) and i == mrow - 1 - zeroVectorSwap:
                        zeroVectorSwap += 1
            doSum = False
            curCol += 1
            curRow += 1
    return determinant

### Fungsi Main Determinan

Fungsi yang telah dibuat tadi akan dijalankan di "if __name__ == '__main__':" block dengan input matrix 4x4 yaitu:

    |  4  6 -3 -2 |
    | -8 -1  8 -3 |
    |  9  9 -2 -3 |
    |  4 -5  3  7 |

In [16]:
if __name__ == '__main__':
    matrix = np.array([4, 6, -3, -2, -8, -1, 8, -3, 9, 9, -2, -3, 4, -5, 3, 7], dtype=np.float64).reshape(4, 4)
    print(f'Determinant: {gaussDeterminant(matrix)}')

Input Matrix
[[ 4.  6. -3. -2.]
 [-8. -1.  8. -3.]
 [ 9.  9. -2. -3.]
 [ 4. -5.  3.  7.]]

Iteration: 1
Dividing Row 1 by 4.0
[[ 1.    1.5  -0.75 -0.5 ]
 [-8.   -1.    8.   -3.  ]
 [ 9.    9.   -2.   -3.  ]
 [ 4.   -5.    3.    7.  ]]

Iteration: 2
Subtracting Row 2 by [ -8. -12.   6.   4.]
[[ 1.    1.5  -0.75 -0.5 ]
 [ 0.   11.    2.   -7.  ]
 [ 9.    9.   -2.   -3.  ]
 [ 4.   -5.    3.    7.  ]]

Iteration: 3
Subtracting Row 3 by [ 9.   13.5  -6.75 -4.5 ]
[[ 1.    1.5  -0.75 -0.5 ]
 [ 0.   11.    2.   -7.  ]
 [ 0.   -4.5   4.75  1.5 ]
 [ 4.   -5.    3.    7.  ]]

Iteration: 4
Subtracting Row 4 by [ 4.  6. -3. -2.]
[[  1.     1.5   -0.75  -0.5 ]
 [  0.    11.     2.    -7.  ]
 [  0.    -4.5    4.75   1.5 ]
 [  0.   -11.     6.     9.  ]]

Iteration: 5
Dividing Row 2 by 11.0
[[  1.     1.5   -0.75  -0.5 ]
 [  0.     1.     0.18  -0.64]
 [  0.    -4.5    4.75   1.5 ]
 [  0.   -11.     6.     9.  ]]

Iteration: 6
Subtracting Row 3 by [-0.   -4.5  -0.81  2.88]
[[  1.     1.5   -0.75  -0.5

### Bandingkan Dengan Fungsi BuiltIn Numpy

Kita bandingkan determinan sebelumnya dengan determinan yang dihitung dengan cara SMA menggunakan numpy.linalg.det(). Hasilnya berbeda tapi tidak jauh, perbedaan tersebut keluar akibat error pada perhitungan karena perhitungan kita cuma 2 angka dibelakang koma.

In [17]:
if __name__ == '__main__':
    matrix = np.array([4, 6, -3, -2, -8, -1, 8, -3, 9, 9, -2, -3, 4, -5, 3, 7], dtype=np.float64).reshape(4, 4)
    print(np.linalg.det(matrix))

970.000000000001
